
on:
 push:
   branches:
     - main
   paths-ignore:
     - 'templates/*.json'
     - 'config/*.json'
     - 'locales/*.json'
 pull_request:
   branches:
     - main
   paths-ignore:
     - 'templates/*.json'
     - 'config/*.json'
     - 'locales/*.json'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  # Отступ исправлен
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge-UK
        with:
          github_token: ${{ github.token }}
          source: 'main'
          target: 'dev'
